### ISSUE TITLE
Side bar is empty

### ISSUE THREAD

**Issue by coka** [tari-project/block-explorer-frontend#105]
If all links have been removed from the side bar, would it make sense to remove it?

P.S. Somewhat related—have you considered openly publishing the design files for this project? It could help with onboarding new contributors.

**Comment by Krakaw** [comment]
We can remove it and re-introduce it when there are things to put in.

**Comment by c-franklin** [comment]
I can take this. 

On the second issue - which design files? 
Could potentially create a gitbook style guide.

**Comment by delta1** [comment]
Not sure who did the designs, or how outdated they are now.. @Krakaw any pointers?

**Comment by stringhandler** [comment]
![image](https://user-images.githubusercontent.com/4200336/109476859-0ac4bc00-7a80-11eb-8552-7cf8efb25565.png)

I suggest, move logo into container on the right and remove the side bar

**Comment by delta1** [comment]
Should appear as such: 

![image](https://user-images.githubusercontent.com/351403/109477059-42cbff00-7a80-11eb-9b65-aa68ffa8bda2.png)


I did this in the inspector by: 
- removing the border-right on the logo 
- removing the div class="sidebar"

**Comment by delta1** [comment]
@charlottefranklin issue updated ^^

**Comment by gringokiwi** [comment]
@charlottefranklin you doing this?

**Comment by delta1** [comment]
@jamesscaur go ahead, I think Charlotte was working on another issue when she had time 👍

**Comment by gringokiwi** [comment]
cool thanks @delta1, I have some time tomorrow in my evening, I still need to get the code working on my machine, but it seems like you guys have made it quite easy. I'll see if I can knock off some other issues too.

**Comment by delta1** [comment]
@jamesscaur it’s even easier to just set up this repo and point it at the live server 

https://github.com/tari-project/block-explorer-frontend/issues/3#issuecomment-780534226

**Comment by gringokiwi** [comment]
Oh, excellent, that's going to save me time thanks


Apr 12, 2021, 16:11 by ***@***.***:

**Comment by c-franklin** [comment]
@jamesscaur - check the readme for easy way to run locally.

**Comment by gringokiwi** [comment]
Hi team sorry - I did get the repo running on my machine, but I haven't got enough time available to fix this this week or next. Can someone else take this issue? I'll try to contribute to tari some other time :)

**Comment by delta1** [comment]
Hey @jamesscaur no worries!
