### ISSUE TITLE
Historical Hash Rate chart - newest block should be on the right

### ISSUE THREAD

**Issue by stringhandler** [tari-project/block-explorer-frontend#118]
On the Historical Hash Rate chart :
![image](https://user-images.githubusercontent.com/4200336/109475025-db14b480-7a7d-11eb-8184-0b1a125a5afa.png)

The x-axis should be reversed so that the newest (highest) block is on the right and the oldest block is on the left. It is currently the other way around

**Comment by sachinh19** [comment]
I would like to take a go at this one if no one else is already working on it. I have a couple of questions though.

- Are there any contributing guidelines to follow?
- If there aren't any, my second question is, what sort of tests are to be run to be able to open a PR?

**Comment by stringhandler** [comment]
Go for it! There aren't any tests yet, but it must pass the lint CI here: https://github.com/tari-project/block-explorer-frontend/blob/development/.github/workflows/lint.yml

**Comment by sachinh19** [comment]
@mikethetike this can be closed now if the PR has fixed the issue

**Comment by delta1** [comment]
Thanks @sachinh19 for the PR, will be included in the next release 👍
