### ISSUE TITLE
[Feature] Latest Blocks card

### ISSUE THREAD

**Issue by lsquaredleland** [tari-project/block-explorer-frontend#14]
⚠️ **NOTE: TOP GRAPHIC OF THE CHART IS STILL WIP, THE REST HOWEVER IS FIXED** ⚠️

What is an overview of the latest content inside of a block? How many transactions where in it, how long did it take to mine, how full was the block?

**Zeplin**: 
TODO -> this asset has to be updated

**Specs**
* Show the latest n-blocks of the blockchain depending on the width of the screen
* Each sub component should contain
   * The total number of transactions within the block
   * The time to mine the block in mm:ss
   * The total size of the block in kilobyte
* The top half of the graph is still a WIP, please leave a placeholder for now

**Acceptance Criteria**
* The latest block should be on the right side of the screen, with the oldest on the left hand side
* User can scroll laterally to see older blocks
* As a new block gets mined, a new card item should appear on the right side of the screen with the older cards shifting to the left

**Open Questions**
* What should the top of the graph of the card be?

**Comment by Krakaw** [comment]
> The top half of the graph is still a WIP, please leave a placeholder for now
@lsquaredleland any update on this?

**Comment by lsquaredleland** [comment]
Still working on it

**Comment by Krakaw** [comment]
Initial implementation is complete.
