### ISSUE TITLE
Fix block explorer front end displays zero encrypted value

### ISSUE THREAD

**Issue by hansieodendaal** [tari-project/block-explorer-frontend#145]
_This output from the block explorer:_

![Image](https://user-images.githubusercontent.com/39146854/194330551-6beb8f1f-6015-47f6-841a-fe412de9e656.png)

**Note:** It is not possible for `pub fn encrypt_value(..)` in `tari-project` to give zeros as it has a non-zero payload tag that is added to the AEAD..

**Comment by stringhandler** [comment]
I haven't seen this again  since
