### ISSUE TITLE
[Feature Block View]

### ISSUE THREAD

**Issue by lsquaredleland** [tari-project/block-explorer-frontend#20]
What do historical blocks look like? This chart shows the contents of an individual block (`kernels`, `inputs` and `outputs`) in an interactive visualization. Along with the percentage of the block that is filled.

**Zeplin**: 
[Abstract](https://app.abstract.com/projects/9d7d3fe3-a5bd-48ce-b03a-6b51ab3a2eb5/branches/2fa4ae70-2dc9-40b9-8498-f9f2a999dea5/commits/6170167938db17ab04aa4f3770886d50e182d700/files/6db9c963-4fba-4aee-934e-35b70c01093b/layers/FC06F1AA-1849-4A85-946D-0AB2E8E4609F?mode=design)

**Specs**
* For the visualization can look here for starter code https://observablehq.com/@d3/clustered-bubbles

**Acceptance Criteria**
* Tooltips should have the type of item at the the top (`kernel`, `input`, or `output`) AND on a new line the first 10 characters of the commitment hash.
* For the main graph each distinct group of items should have their own coloring and have a key
* Below the main visualization the block filled bar should accurately represent how filled the block is. There should be up to 3 fraction digits, while for percentage up to 1 fraction digit.
* There should be a hierarchy between `Mining Data` and `Technical Data`
* User should be able to navigate to this page by searching for a specific block hash or clicking on a specific block in the landing page.

**Open Questions**
* What should the tooltips

**Comment by Krakaw** [comment]
Closed by #52
