### ISSUE TITLE
[Feature] Top level network statistics

### ISSUE THREAD

**Issue by lsquaredleland** [tari-project/block-explorer-frontend#7]
Enable users to quickly understand top level statistics of the network within the last 24 hours (along with other available time frames)

**Zeplin**: 
TODO

**Specs and Assets**
* Fields: `Total Txns`, `Average Txns/second`, `Hashrate`, `Average Fee`, `Average Block Time`, `Average Block Weight`
* Main Font
   * font-family: Avenir-Black
   * font-size: 35px
* Sub Header
   * font-family: Avenir-Roman;
   * font-size: 12px;
* dropdown options: `Past 1hr`, `Past 24hrs`, `Past 7d`, `Past 30 d`, `Past 1yr`, `Since Inceptions`. Default to `Past 24hrs`

**Acceptance Criteria**
* When switching different time horizons the associated numbers should update accordingly.
* Numbers should at most have 1 decimal of precision unless the number is less than 0. (i.e. 83.54k -> 83.5k, but 0.0028 is ok)
* Hash rate should have the correct units associated with it (unsure of what numbers you'll get back from the backend but [here](https://en.bitcoinwiki.org/wiki/Hashrate#How_is_the_hash_rate_measured.3F) is a conversion table

**Comment by coka** [comment]
Has everything here apart from the dropdowns been implemented?

**Comment by Krakaw** [comment]
Yeah, it's just the dropdowns.

**Comment by stringhandler** [comment]
I agree that this would be nice, but at the moment I have no idea where these design elements would go, so closing for now. Will reopen if there are designs added
