### ISSUE TITLE
[Feature] Blocks Overview

### ISSUE THREAD

**Issue by lsquaredleland** [tari-project/block-explorer-frontend#8]
How many transactions have there been in the last n-number of blocks? This chart here shows the "weight" of the most recent blocks. Weight refers to how much data is contained within the block, it is comprised of 3 different elements: `kernels`, `inputs` and `outputs`. Each one technically has a different weight, but for now let's ignore that.

By quickly scanning this chart, viewers can infer how active the network is.

**Zeplin**: 
TODO

**Specs**
* y-axis is `Block Weight`, note that because there is a maximum size of a Tari block -> there will be a ceiling on this value.
* x-axis is time in h:mm format
* Spacing between each block is dependent on the block time between each other. If block A was generated at 10:01:05 and block B was generated 10:03:10, then the space between them should be 125 seconds. (Average time is 120 seconds between blocks)
* dropdown options: `Past 1hr`, `Past 6hrs`, `Past 24hr`. Default to `Past 6hrs`. (This translates roughly to 180 bars on the screen
* Tooltips are still WIP

**Acceptance Criteria**
* Graph should automatically update whenever there is a new block, ideally with an animation where the existing bars are sliding to the left.

**Open Questions**
* Should there even be a dropdown, or should the view be purely the last n-number of blocks.
* What should the tooltips look like?

**Comment by Krakaw** [comment]
We'll need to implement tari-project/blockchain-explorer-api#6

**Comment by coka** [comment]
I would suggest closing #7, #8, #9, and #13, and creating a separate issue for the dropdowns. 🤔
